version: '3'

services:
  cors-auth-proxy:
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cors.rule=Host(`cors.${DOMAIN?:err}`) || HostRegexp(`{subdomain:[a-zA-Z0-9]+}.${DOMAIN?:err}`)"
      - "traefik.http.routers.cors.service=cors"
      - "traefik.http.services.cors.loadbalancer.server.port=8080"

networks:
  traefik_default:
    external: true
